#ifndef KEYBOARDS_CHIBIOS_TEST_TEENSY_LC_ONEKEY_CONFIG_H_
#define KEYBOARDS_CHIBIOS_TEST_TEENSY_LC_ONEKEY_CONFIG_H_

#include "../config.h"
#define MATRIX_ROWS 5
#define MATRIX_COLS 14
#define RGB_DI_PIN 23
#define RGBLED_NUM 3
#endif /* KEYBOARDS_CHIBIOS_TEST_TEENSY_LC_ONEKEY_CONFIG_H_ */
